### ISSUE TITLE
Feature Request: Disable default icons

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#101]
Apologies if I am overlooking the option, I'd like to be able to remove the default icon that spawns when an action is assigned to a button, but no custom icon has been assigned. It would still appear even if I had added a text label.

**Comment by Core447** [comment]
You can just add an empty alpha image to the key.

**Comment by v4u6h4n** [comment]
Apologies, I probably should have worded my initial message a little more clearly; I don't actually need this feature myself, because I always use custom icons anyway, but I was thinking that it might be an issue for other users who just want to use labels without an icon, especially if they are a little less tech savvy.

I was thinking using the trash can you have for custom icons would do the trick, which could be replaced with the revert arrow you have for other areas, like labels.

But yeah understand if it's not worth implementing.

**Comment by Core447** [comment]
Ok, that's a great idea, I just don't know how to implement it in the ui, yet.
