### ISSUE TITLE
Devise assignment for Auto Change Page

### ISSUE THREAD

**Issue by oparada1988** [StreamController/StreamController#102]
**Describe the feature idea**
Add device assignment for the Auto Change Page option

**Additional context**
I  just realized you can do automatic windows switch based on the application window. One thing I notice was that for example, i created a page for inkscape. I want the inkscape shortcuts to show up in my XL device. However, the page will only show up in the regular stream deck. I belive for the automatic page switch there should be an option to select which device the page will appear

![Untitled](https://github.com/StreamController/StreamController/assets/4031078/7b0ed824-40b1-4082-92a7-920929a89b67)

I have been messing with it, and no matter what the automatic page switch will happen on both devices
not on the specific device I want

**Comment by Core447** [comment]
Implemented with 82de25ed11f4184531d318f2e71294950c5d6f75. This will be available on Flathub with the next release
