### ISSUE TITLE
BUG: Search results include partial matches to words

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#104]
Maybe this is expected behaviour, but when I use the search function in the page editor, the search results match not only the word I input, but also matches parts of the word, like if I input `maintenance` it will include results that match `main` and `maintenance` instead of only results that match `maintenance`. It makes searching a lot less useful for me, because it sometimes gives me heaps of results that partially match when there is only one result that is an exact match.

**Comment by Core447** [comment]
Changed with 441070a41a94a20553a28a4dd8f73a7f44925cc3

**Comment by v4u6h4n** [comment]
Thanks :-)
