### ISSUE TITLE
BUG Plugin downloads seem to depend on unauthenticated Git access

### ISSUE THREAD

**Issue by milochristiansen** [StreamController/StreamController#107]
**Describe the bug**
When downloading plugins from the store, if the download fails due to a git error they are still reported as successfully installed.

Running the app from a shell gives the following log message:
```
Cloning into '/home/milo/.var/app/com.core447.StreamController/data/plugins/com_core447_OSPlugin'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
sh: line 1: cd: /home/milo/.var/app/com.core447.StreamController/data/plugins/com_core447_OSPlugin: No such file or directory
2024-05-13 12:21:44.341 | INFO     | src.backend.DeckManagement.DeckController:load_page:582 - Loading page Discord on deck A00DA41310OX
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x752d8c938780 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x592cec2d4d30)>>
2024-05-13 12:21:44.410 | INFO     | src.backend.DeckManagement.DeckController:load_page:612 - Loaded page Discord on deck A00DA41310OX
2024-05-13 12:21:44.431 | SUCCESS  | src.windows.Store.StoreBackend:install_plugin:693 - Plugin com_core447_OSPlugin installed successfully under: /home/milo/.var/app/com.core447.StreamController/data/plugins/com_core447_OSPlugin with sha: d208a196bf97369b55df923ab8a5130961485481
```

My system Git is keyed to a smart card, and will give that error until the smart card is unlocked, *however* unlocking the smart card does not fix the error in this case leading me to believe that maybe Flatpak is doing something weird to the connection that prevents my key from being seen. The system git should probably not be used like this!

There are multiple layers of bug here, since not only is the app apparently using the system git config improperly, it is also not recognizing that there was an error at all.

**To Reproduce**
1. Configure system Git with increased security.
2. Open the store.
3. Try to download any plugin.

**Expected behavior**
I would expect the download to work. However, it doesn't.

**Comment by milochristiansen** [comment]
Removing
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```
From my `.gitconfig` allows me to download plugins, however this solution is *absolutely unacceptable* for a huge number of reasons unrelated to this application.

**Comment by Core447** [comment]
Ok, yeah another problem is that the app writes the plugin repos in the user's .gitignore. I'm going to try to find a way to completely sandbox git. For now you can just manually clone the plugin repos into data dir (`~/.var/app/com.core447.StreamController/data/`). It might be necessary to rename the folders after the clone to match the ids specified in `manifest.json`.

Sorry for the inconvenience - I hope to find find a solution soon

Edit: Seems like [this](https://github.com/cli/cli/issues/7420) issue is pretty similar

**Comment by Core447** [comment]
Can you please check if changing the filesystem permissions in Flatseal to these values solves the problem for you?:
![image](https://github.com/StreamController/StreamController/assets/100139110/3652c69b-212e-4900-a5f6-5519532a369f)

**Comment by milochristiansen** [comment]
That worked!

**Comment by Core447** [comment]
Ok, I'm going to make this the default for the next release
