### ISSUE TITLE
[Feature] Add on_key_hold functionality

### ISSUE THREAD

**Issue by gensyn** [StreamController/StreamController#110]
I know you have been tossing the idea around to also give actions the ability to react to a button being held for a longer-than-normal amount of time - we have briefly discussed it on Discord and that it is quite complex. I kept thinking about it and would like to share my thoughts.

**This is my use case:**
I have a button which controls my media player - pressing it toggles play/pause. I would like to long press that button to get to a different page with further media control buttons (volume up/down etc). Long pressing should not toggle play/pause.
So if we added _on_key_hold_ to trigger after, let's say, one second I could change the Change-Page-action of DeckPlugin to allow to customize which button state should trigger the page change. But that would still trigger the play/pause-toggle on my button since I have to bind that to either _on_key_down_ or _on_key_up_. So to prevent that, after a long press _on_key_up_ should not be executed.
With these changes I could build my button: Toggle play/pause with _on_key_up_ and do a page change with _on_key_hold_ which then doesn't trigger _on_key_up_.

That would fit my use case but would break some others. First of all, existing plugins would not execute _on_key_up_ if someone pressed a button for slightly too long.
And to stay with my Home Assistant example: What if I wanted to (e.g.) toggle a light on when pressing a button, keep it on for however long the button is pressed and toggle it off again when releasing the button? When _on_key_up_ is just omitted, this functionality would become impossible.
So I came up with the idea to introduce a second _on_key_up_ event: _on_key_hold_up_. When a button is released, it is checked whether the button was held or not and either _on_key_up_ or _on_key_hold_up_ are executed. For existing plugins I would implement _on_key_hold_up_ to just call _on_key_up_ so nothing needs to be changed where the new functionality isn't desired. I could then expand HomeAssistantPluing and DeckPlugin to behave the way I envision.

I propose these code changes:
* _ControllerKey.press_state_ would turn from boolean to string with possible values "down", "hold" and "up"
* _ControllerKey.on_key_change_ would launch a new Thread when a button is pressed. That Thread sleeps for (e.g.) one second and after it resumes it first checks whether the state is still "down" - if not the button was released in the meantime and the Thread (i.e. the function in the Thread) just quits. If the state is "down", the Thread sets the press_state to "hold" and executes _on_key_hold_.
When a button is released it checks the press_state. "down" trigges the existing _on_key_up_, "hold" triggers _on_key_hold_up_. It then sets the press_state to "up".
* ActionBase would get two new functions:
  * _on_key_hold_ just passes
  * _on_key_hold_up_ calls _on_key_up_

I would then expand HomeAssistantPlugin and DeckPlugin to use this new feature.
I hope you could follow my thoughts. Do you think this is a valid way to go? Do you see issues or deal breakers I didn't think of?
I would be happy to implement this myself.

**Comment by Core447** [comment]
Great idea, I'm going to try to implement it. However, maybe we can also extends @G4PLS AdvancedActions plugin to allow to specify different actions for a short press and long press. This would allow users to create their own combinations.

**Comment by G4PLS** [comment]
Using on_key_up to achive the hold functionality is a really nice Idea.

@Core447 I think I gave a really good way to create the actual Hold Function in the Discord so you should be able to use that as a Base and change it so it works with the proposed Idea

Just so you dont have to search for it here is it again with some explanation aswell!

I use one thread and two events.
One Event handles when the Thread should continue, this is achived with `wait.wait()`. That makes it so it waits until the event is being set. At the end of the thread I clear the event again.

The other event handles when the thread should stop, this would be used when you change the page or remove the button.

tha variable down is just a bool to check when the button is held down, it gets toggled on when the key is down and off when the key is up. 
The ticks count up whenever the key is down, this utilizes the second while loop.

The overall approach makes the thread not that resource intensive because its just idle whenever you dont press the button and is only active when you actually press the button

```python
class DemoHold(ActionBase):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.down = False
        self.ticks = 0

        self.tick_counter_running = threading.Event()
        self.wait_event = threading.Event()

        self.event = threading.Thread(target=self.tick_counter, args=(self.tick_counter_running, self.wait_event,))

    def on_ready(self):
        self.tick_counter_running.set()
        self.event.start()

    def on_key_down(self):
        self.down = True
        self.ticks = 0
        self.wait_event.set()
        print("KEY DOWN")

    def on_key_up(self):
        self.down = False
        print("KEY UP")

    def tick_counter(self, running: threading.Event, wait: threading.Event):
        while running.is_set():
            event_set = wait.wait()

            while self.down:
                self.ticks = self.ticks + 1
                print(f"KEY HELD FOR {self.ticks} TICKS")
                time.sleep(0.5)
            self.wait_event.clear()
```

**Comment by Core447** [comment]
I'm going to try different approaches and come back to you

**Comment by G4PLS** [comment]
Sure, testing other ways could result in an even better outcome! 
My approach is the bare minimum you would need to implement a hold behaviour inside an action without taking any backend into account

**Comment by gensyn** [comment]
Maybe I didn't explain it well enough but I feel my approach is simpler without the tick counting. Just let the thread sleep until the duration of a long press is reached. After that it isn't needed anymore.

**Comment by Core447** [comment]
What do you think of 303f25dfa2eba433479ba2804bf7fbcbe899b3b0 (Edit: wrong sha)?

**Comment by G4PLS** [comment]
> What do you think of [303f25d](https://github.com/StreamController/StreamController/commit/303f25dfa2eba433479ba2804bf7fbcbe899b3b0) (Edit: wrong sha)?

Looks good so far from the Code Perspective.
Would it maybe be possible to make it that Actions can define theyre hold time? Idk how the Deck Controller actually works in relation to the ActionBase

**Comment by Core447** [comment]
Yes that would be possible, but idk if it's worth it and it may be weird if it's not the same for all actions

**Comment by gensyn** [comment]
> What do you think of [303f25d](https://github.com/StreamController/StreamController/commit/303f25dfa2eba433479ba2804bf7fbcbe899b3b0) (Edit: wrong sha)?

Am I missing something? You only implemented the hold_up part of my proposal, right? Nothing is triggered directly when the hold time is reached?

**Comment by gensyn** [comment]
> Yes that would be possible, but idk if it's worth it and it may be weird if it's not the same for all actions

This. If not all actions use the same duration it's gonna be a mess.

**Comment by G4PLS** [comment]
Could we maybe make it something you could change somehow?
I find 0.75 seconds to be really long, but thats just my personal opinion

If thats to much effort for one Person than thats completely fine!

**Comment by Core447** [comment]
> Am I missing something? You only implemented the hold_up part of my proposal, right? Nothing is triggered directly when the hold time is reached?

Do you really think this would be useful? What would be a use case for that that isn't doable with the current up, down and hold_up?

> Could we maybe make it something you could change somehow?

Yes, absolutely

**Comment by gensyn** [comment]
> > Am I missing something? You only implemented the hold_up part of my proposal, right? Nothing is triggered directly when the hold time is reached?
> 
> Do you really think this would be useful? What would be a use case for that that isn't doable with the current up, down and hold_up?
> 
> > Could we maybe make it something you could change somehow?
> 
> Yes, absolutely

You would have instant feedback that you pressed long enough. If you only evaluate the time after key_up you can't be sure that you pressed long enough.

**Comment by G4PLS** [comment]
I mean you could do:
key_down: You press the key and instantly something happens
key_up: You almost instantly release the key and something happens
on_hold_down: You wait 0.75 seconds and something happens
on_hold_up: Happens at the very end basically like key_up, so basically theyre the same

**Comment by gensyn** [comment]
> on_hold_up: Happens at the very end basically like key_up, so basically theyre the same

See my use cases why they are not. At least not the way I see them.

**Comment by Core447** [comment]
Ok, but maybe `on_hold_start` and `on_hold_end`?

> I mean you could do: key_down: You press the key and instantly something happens key_up: You almost instantly release the key and something happens on_hold_down: You wait 0.75 seconds and something happens on_hold_up: Happens at the very end basically like key_up, so basically theyre the same

@gensyn I mean if plugins absolutely need more hold stuff, they can always implement something themselves. This is what the counter plugin does currently.

**Comment by G4PLS** [comment]
> > on_hold_up: Happens at the very end basically like key_up, so basically theyre the same
> 
> See my use cases why they are not. At least not the way I see them.

True, sorry read that wrong
You mean that on_hold_up only triggers after you held the button, so that you can destinquish between a normal keypress and a held keypress

**Comment by G4PLS** [comment]
> Ok, but maybe `on_hold_start` and `on_hold_end`?
> 
> > I mean you could do: key_down: You press the key and instantly something happens key_up: You almost instantly release the key and something happens on_hold_down: You wait 0.75 seconds and something happens on_hold_up: Happens at the very end basically like key_up, so basically theyre the same
> 
> @gensyn I mean if plugins absolutely need more hold stuff, they can always implement something themselves. This is what the counter plugin does currently.

on_hold_start and on_hold_end make a lot more sense! Everything is still seperate and you know what everything is for
And its basically what @gensyn suggested because you have key_down, key_up, hold_start and hold_end

Everything that goes further than these 4 Key Actions should be implemented from the Plugins themself. I think these 4 different actions that can trigger are enough

**Comment by gensyn** [comment]
All in all, yes, this would somehow work for my use case but I still think it would be nice to have the hold event trigger on reaching the set duration, not after releasing the button.

**Comment by G4PLS** [comment]
@Core447 @gensyn from that whole conversation I now got the picture what you both kinda want
And wanted to ask if this looks alright from what you planned @Core447 

![image](https://github.com/StreamController/StreamController/assets/125091918/dfacd33e-0647-401e-9c29-22d83a3a4d1d)

**Comment by gensyn** [comment]
What's the difference between hold_end and key_up?

**Comment by G4PLS** [comment]
> What's the difference between hold_end and key_up?

Theyre seperate events, so you can have the page switch when the hold event ends and the key_up event when the key gets released.

Thats why I said theyre basically the same. But this way you can seperate actions better
For example you have media_skip on key_up and change_page with hold_end

Now it would be youre responsibility to make it function that key_up gets skipped when hold ends
Thats what i got from the conversation, you and core can correct me if I got it wrong

**Comment by gensyn** [comment]
Ah ok, I was confused that they have different timestamps.

**Comment by G4PLS** [comment]
It would make sense that they trigger after each other and not at the same time, thats how i wanted to represent that
So the time between these two triggering is completely random made up from me

**Comment by Core447** [comment]
> Everything that goes further than these 4 Key Actions should be implemented from the Plugins themself. I think these 4 different actions that can trigger are enough

I can add it

**Comment by Core447** [comment]
I created a new branch (´key-hold´) for this feature. what do you think of the current state? We now have `on_key_down`, `on_key_up`, `on_key_hold_start`, `on_key_hold_stop`

**Comment by gensyn** [comment]
Sounds great, thank you. Will test on Tuesday.

**Comment by G4PLS** [comment]
I will test it later or tomorrow

**Comment by Core447** [comment]
Merged it into main

**Comment by gensyn** [comment]
I have been using the feature without problems for a while now and I am really happy about it. Thanks @Core447. :)

**Comment by francisqureshi** [comment]
Is it possible add visual feedback via a button image change when a button has been held and the held action (key_down) has been triggered ?

**Comment by G4PLS** [comment]
Currently this is for plugin devs to decide

**Comment by francisqureshi** [comment]
Interesting! Ah I think I can achieve what I want by adding a state change on the hold starting... Thanks!

**Comment by Core447** [comment]
> Is it possible add visual feedback via a button image change when a button has been held and the held action (key_down) has been triggered ?

Interesting idea! Maybe a thin orange border when the minimum time for hold has been reached?

**Comment by francisqureshi** [comment]
Yeah totally! I ended hacking this together via state and an image with a transparent softened edge:

![Image](https://github.com/user-attachments/assets/fb2a94b0-35a6-46a2-af45-beec2769ed3e)

Then change the background colour (to blue as above) to show the hold has happened - it's a bit precarious though, and I think a built in solution would be amazing!
