### ISSUE TITLE
BUG Installing StreamController in ubuntu 24.04

### ISSUE THREAD

**Issue by MikeLemo1** [StreamController/StreamController#120]
**Describe the bug**
can't run `python3 main.py` after installationg according to the installation doc:
https://streamcontroller.github.io/docs/latest/installation/

**To Reproduce**
1. Go to https://streamcontroller.github.io/docs/latest/installation/
2. follow the instructions (tested with python 3.12 and 3.11 `python3.11 -m venv .venv`) 

**Expected behavior**
Actually open the StreamController app...

**Screenshots**
```bash
Traceback (most recent call last):
  File "/home/pong/Downloads/StreamController/main.py", line 35, in <module>
    from src.app import App
  File "/home/pong/Downloads/StreamController/src/app.py", line 28, in <module>
    gi.require_version("Xdp", "1.0")
  File "/home/pong/Downloads/StreamController/.venv/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xdp not available
```

**Additional context**

**Comment by Core447** [comment]
Have you made sure that you have these packages: `xdg-desktop-portal xdg-desktop-portal-gtk libportal libportal-gtk4`?

**Comment by MikeLemo1** [comment]
I think not sure did 
`sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk libportal libportal-gtk4` but it says 

>Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libportal
E: Unable to locate package libportal-gtk4

if there isn't any other easy way to install em or do you have to install each manually on ubuntu, also tried the flatpak method but when I try to open it through flatpak it prints the following error message:
`ldconfig failed, exit status 256`
So not much luck through flatpak either.

**Comment by Core447** [comment]
For the flatpak:
Can you please try if [this](https://github.com/flatpak/flatpak/issues/5081#issuecomment-2013938759) fixes your problem?

For the source version:
Can you retry after installing `libportal-gtk4-1`?

**Comment by MikeLemo1** [comment]
Yes the 
```bash
sudo chown -R your_username:your_username /home/your_username/.var/app
sudo chmod -R 744 /home/your_username/.var/app
```
did the job. Thanks!

No I got some basic questions before I start pursuing my kind mess, what is the philosophy behind setting individual keypress combos in this app? do you just use a "Run Command" from OS tab in "Add action" along with xdotools legacy coding? or did I miss something?

**Comment by Core447** [comment]
> did the job. Thanks!

Nice!

> No I got some basic questions before I start pursuing my kind mess, what is the philosophy behind setting individual keypress combos in this app? do you just use a "Run Command" from OS tab in "Add action" along with xdotools legacy coding? or did I miss something?

Yes, either this, or you can use the Hotkey action of the OS plugin. If you don't see it, you might have to add [this](https://github.com/streamcontroller/osplugin?tab=readme-ov-file#hotkeys--write-text) udev rule and restart your computer.

**Comment by MikeLemo1** [comment]
Yes creating a file called "01-my-first-udev.rules"  in  '/usr/lib/udev/rules.d/' with the following
`KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", GROUP="input", MODE="0660"` did the job.
It's just wierd that instead of warning about it in the streamcontoller app it's hidden throwing new users off a bit.

Anyways thank you alot for the help we'll stay in touch throughout this repo's dev journey I guess!

**Comment by Core447** [comment]
> It's just wierd that instead of warning about it in the streamcontoller app it's hidden throwing new users off a bit.

Thanks for your feedback, you're right hiding it is a bit inconvenient, I'm gonna change it soon

> Anyways thank you alot for the help we'll stay in touch throughout this repo's dev journey I guess!

You're welcome! If you want, you can also join the [Discord](https://discord.gg/MSyHM8TN3u).

**Comment by ThibF** [comment]
Also building on 24.04, I have the same issue without going through flatpack.
I have installed : 
xdg-desktop-portal xdg-desktop-portal-gtk libportal-gtk4-1 libportal1

Without success, pip still fail to build:
```
      Not looking for a fallback subproject for the dependency gobject-introspection-1.0 because:
      Use of fallback dependencies is disabled.
      
      ../meson.build:29:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.
```

Then installed : `libgirepository1.0-dev` and was able to complete the installation.
I guess documentation might need to be updated.

**Comment by gazhay** [comment]
Just hit this bug.

Firstly got platform 47 errors, but once I installed those it builds then

```
flatpak run com.core447.StreamController
Traceback (most recent call last):
  File "/app/bin/StreamController/main.py", line 39, in <module>
    from src.app import App
  File "/app/bin/StreamController/src/app.py", line 24, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/app/bin/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 20, in <module>
    import globals as gl
  File "/app/bin/StreamController/globals.py", line 9, in <module>
    from src.backend.DeckManagement.HelperMethods import find_fallback_font
  File "/app/bin/StreamController/src/backend/DeckManagement/HelperMethods.py", line 36, in <module>
    from autostart import is_flatpak
  File "/app/bin/StreamController/autostart.py", line 21, in <module>
    gi.require_version("Xdp", "1.0")
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xdp not available

sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk libportal libportal-gtk4
[sudo] password for gaz: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libportal
E: Unable to locate package libportal-gtk4
```

I generally don't run flatpaks but aren't they containerised? 

Also permissions on ~/.var directories are fine

Also just tried the flatpak install isntructions from 
```https://flathub.org/en/apps/com.core447.StreamController/install```

```flatpak run com.core447.StreamController.flatpakref
error: app/com.core447.StreamController.flatpakref/x86_64/master not installed
```

but 
```
StreamController                                com.core447.StreamController                        1.5.0-beta.11                  stable            flathub               system
```
It is installed

**Comment by ImDevinC** [comment]
@gazhay did you build the flatpak from source, or did you install from Flathub?

**Comment by gazhay** [comment]
> @gazhay did you build the flatpak from source, or did you install from Flathub?

In order i did

1. Install with instructions on GitHub 
2. Removed
3. Installed flatpak via download and flatpak install cli
4. Got the dependency issues
5. Removed
6. Installed from ubuntu store 
7. Launched ok

Not really sure what was going on, as I say, not a usual flatpak user, but got there i  the end.

**Comment by ImDevinC** [comment]
Thanks for clarifying. The list you provided doesn't _quite_ narrow down what was done as there are multiple installation instructions on GitHub, and step 3 doesn't really clarify if you built the flatpak locally or installed through flathub (IE: `flatpak install flathub com.core447.StreamController`).
That being said, glad you got it resolved, although I don't know what version is on the Ubuntu store so hopefully it's kept up to date

**Comment by gazhay** [comment]
(1)

<img width="1737" height="266" alt="Image" src="https://github.com/user-attachments/assets/7c12a712-6940-4be3-b69d-a2e88c18b036" />

(3) https://flathub.org/en/apps/com.core447.StreamController/install  And downloaded https://dl.flathub.org/repo/appstream/com.core447.StreamController.flatpakref
Installed with ```flatpak install <downloaded file>```

(6) Was clicking the "install" button https://flathub.org/en/apps/com.core447.StreamController which opened ubuntu app store and then I clicked install again.

Like I said its working now. 
If I get some free time I might delve into the code as I have a neo and try to see if the extra controls and screens can be made to work - but not right now.
