### ISSUE TITLE
BUG - StreamController Leads to Popping from S/PDIF Audio Device

### ISSUE THREAD

**Issue by ProjectAzar** [StreamController/StreamController#127]
Here's maybe an odd one. 

Brief Description:
While StreamController is running and buttons are assigned to adjust the volume of my primary output device, the device will pop loudly about 2 seconds after audio stops and whenever audio starts. The probably ends when StreamController is no longer running, the StreamDeck is disconnected, or when the buttons are no longer assigned.

1. Install StreamController from Flathub.
2. Assign buttons to mute, increase volume, and decrease volume of primary audio controller. 
3. Popping behavior begins when device starts or stops receiving audio. It pops between one to two times as if the device is going to sleep.

Expected behavior:
No popping.

System Description:
CPU: AMD 5800X
GPU: Nvidia RTX 4070
Motherboard: Asus TUF Gaming X570-Plus Wifi
Audio Device: Starship/Matisse Digital Audio (built in digital audio device on motherboard)
Speakers: Logitech Z906 5.1 system connected via S/PDIF
OS: Kubuntu 24.04
StreamDeck: StreamDeck +

Diagnostic Steps:
The popping was reminiscent of an audio sleep issue I've had before so I've attempted to set the power_save and power_save_controller variables to off in snd_hda_intel, but no joy. I noticed the popping was not occurring when I rebooted or logged in, which made me think disabling power saving solved the problem, but I noticed that whenever I'd login, my button configurations would stop working. The mute button for my El Gato mic would continue to work, but the mute, volume up, and volume down options would fail for the primary audio device. I noticed StreamController appeared to forget that I set the output device as the primary output device. As soon as I set the output device correctly for each button in StreamController, the audio popping would occur.

Additional Thoughts:
This could be unrelated to StreamController, and it is only because of StreamController I'm detecting a different configuration issue; however, because the issue resolves itself when I stop using StreamController, I'm filing the bug report here. 

I've also not yet been able to test the speaker with analog output or with another set of speakers. I'll try that in the near future.

**Comment by Core447** [comment]
Ok, this is indeed a interesting bug... Which plugin are you using for the volume control?

**Comment by ProjectAzar** [comment]
Edit: Said the wrong plugin. 

I was using AudioControl with the Adjust Volume and Mute actions.

**Comment by ProjectAzar** [comment]
Just a little more diagnostic information. 

I've reinstalled StreamController from Flathub (like I did before), but this time kept the physical Stream Deck Plus disconnected. I've setup a fake deck using the same plugins and recreated the setup I had before. This time, no popping. 

Narrowing this down will probably take me a few days, but it could be an issue with how StreamController is interfacing with the physical deck, it could be something with my Kubuntu setup, it could be something with the AudioControl plugin, or it could be computer gremlins. I'll see if I can eliminate more of these possibilities over the next week.

**Comment by ProjectAzar** [comment]
Last comment for tonight. I setup the physical device again, as I was having no issues with the FakeDeck. Now it decides to work without popping. I'm blaming the gremlins. 

I'll leave this open for a day and, assuming all goes well, I'll close this report tomorrow.

**Comment by Core447** [comment]
Alright. Unfortunately I can't help you debug this because I don't have the popping (and not SD Plus)

**Comment by ProjectAzar** [comment]
No worries, but thanks for taking a look.

I'm closing this one as, for whatever reason, the popping has stopped. I have no information as to what caused the popping to stop, but my resolution process is listed below:

1. Remove the physical device from the system. 
2. Fully remove StreamController from the system. 
3. Reinstall through Flathub. 
4. Create a Fake Deck with the same buttons programmed as when the popping occurred.
5. Reconnect the physical device. 

I do not believe adjusting power saving of the sound device nor reconnecting the S/PDIF connector did anything to resolve this issue, but they couldn't hurt here. 

As such, my problem is resolved, even if it appears to have only been computer gremlins in the first place.
