### ISSUE TITLE
BUG Indexed/paletted PNGs lose transparency

### ISSUE THREAD

**Issue by TheNullicorn** [StreamController/StreamController#137]
**Describe the bug**

Palette-based / indexed PNGs used as icons are stripped of transparency. That is,
On the deck:
1. Semi-transparent pixels are made fully opaque
2. Fully transparent pixels are replaced with black

In the UI:
1. Semi-transparent pixels are preserved, but blended with a default grey color
2. Fully transparent pixels are replaced with the same grey color

The latter means that background colors and/or images are completely obscured by black for affected button.

**To Reproduce**

Assign an indexed PNG to a button.

**Expected behavior**

Transparent pixels are blended with the background, like with non-indexed PNGs.

**Images**

(Sample icons: [indexed](https://github.com/StreamController/StreamController/assets/64789500/8ad30d8c-fb23-450c-812e-ca797ac788f7), [non-indexed](https://github.com/StreamController/StreamController/assets/64789500/4156c44f-8928-4bdf-a451-31a9997469ab))

<p float="left">
    <img src="https://github.com/StreamController/StreamController/assets/64789500/2cb7215b-b064-4199-9aff-4a000d0d8a6b" title="UI with no icon, for reference" />
    <img src="https://github.com/StreamController/StreamController/assets/64789500/6ee70480-9bc4-413f-b9ef-a70949d1483c" title="UI with indexed icon, rendered incorrectly" />
    <img src="https://github.com/StreamController/StreamController/assets/64789500/46dd0a7d-c236-48ba-b6b9-7616e2fbc297" title="UI with non-indexed icon, rendered correctly" />
</p>

<p float="left">
    <img src="https://github.com/StreamController/StreamController/assets/64789500/d34128d3-e041-49d4-b7ad-58c54a52d0c2" title="Deck with indexed icon, rendered incorrectly" />
    <img src="https://github.com/StreamController/StreamController/assets/64789500/23176015-b6c3-44b0-8246-db54f1cc7e95" title="Deck with non-indexed icon, rendered correctly" />
</p>

**Comment by Core447** [comment]
Thanks for reporting this!

f1ad2453c9b3d1de5118781bcb94597f056aee9e should fix this. Now the images look like this (same in the ui and the deck): 
![image](https://github.com/StreamController/StreamController/assets/100139110/bbb8e4b4-3bed-4b02-8866-01b85d3e3881)

I'm gonna keep this open until it hits the Flatpak with the next release
