### ISSUE TITLE
Transition directly from "Choose An Action" into "Configure Action"

### ISSUE THREAD

**Issue by TheNullicorn** [StreamController/StreamController#139]
**Describe the feature idea**
When adding an action with at least one [config row](https://github.com/StreamController/StreamController/blob/fcc9bb2b9514837a07cf655614ee4dbc9557227f/src/backend/PluginManager/ActionBase.py#L257-L258), it would be convenient if its "Configure Action" menu was opened right away. Currently the panel returns to the button's overview and the new entry has to be clicked to configure it.

A setting to at least switch to this behaviour would be nice.

**Comment by Core447** [comment]
Thanks for the idea!

This is actually already implemented in the app, but we changed the internal var name at some point, and most (at least all official) plugins still use the old name. Usually, I would just directly update all of them and push them to the store, but we started working towards the next release and the plugins are already no longer backward compatible, so we'll have to wait until the next release for this change, sorry.

We can keep this open until the plugins have been updated.
