### ISSUE TITLE
BUG Importing pages between different computers does not work

### ISSUE THREAD

**Issue by Jestzer** [StreamController/StreamController#149]
**Describe the bug**
When I import either a single or multiple pages from one computer to another (both running Pop!_OS with Stream Deck Originals), the page seemingly imports when I look at the contents of ~/.var/app/com.core447.StreamController/data/pages/ and the .json file(s)' contents. However, the Stream Deck and the program's GUI only show the imported page(s)' name, nothing else. The page appears blank otherwise.

**To Reproduce**
1. Export a single page or export all of them with the "Export All" button
2. On a different computer, import the page(s) with the "Import" "Page(s)" selection or "StreamController" selection
3. The name of the page(s) will appear, but they will all appear blank. The actual .json files don't reflect this and show all the imported information.

**Expected behavior**
The expected behavior is that importing a page or pages will include all of the customizations made to the page, including icons, actions, etc. on each button.

I have noticed that importing pages on the same computer seems to work fine. I have made sure to include the same assets between each computer before importing.

I have attached a page that imports as blank for me.
[Home 1.json](https://github.com/user-attachments/files/16054231/Home.1.json)

**Comment by Core447** [comment]
Thank you for the detailed report! It seems that I don't have this problem... Have you made sure that the other computer (where you're importing) has all the plugins used by the page(s) installed?
![Untitled](https://github.com/StreamController/StreamController/assets/100139110/8fae22ad-33b7-4e39-ad79-f54db1eb131b)

**Comment by Jestzer** [comment]
Hi Core, thank you for the prompt response and I apologize for not getting back to you sooner. When I'm importing, I don't see an option to "Install missing plugin", so I'll assume the answer is yes, but if there's a more definitive way to confirm this, please let me know. I couldn't find anything related to plugins in the UI's settings.

**Comment by Core447** [comment]
No worries. The option is shown in the sidebar where you can add and manage actions. However, adding a screen asking whether the app should install missing plugins during the import might be a nice qol feature.

**Comment by Jestzer** [comment]
Understood. I'll play around with this a bit more when I access to the computer I'm attempting to export to again, which should be about 4-5 days from now.

**Comment by Jestzer** [comment]
I can't seem to reliably reproduce the issue, but I think it was related to importing pages with the same name. Only once did I receive an error that I couldn't import it due to this reason. This resulted in 2 other issues that I was able to workaround by simply restarting the program. I'm going to close this for now. Thank you for your assistance.

**Comment by Core447** [comment]
Ok, I'll try to debug this

**Comment by Core447** [comment]
When importing a single page which name is already used the user will be prompted to change it's name. However, for an import of multiple/all pages this doesn't happen, instead they override the present pages.
