### ISSUE TITLE
UI Unresponsive

### ISSUE THREAD

**Issue by objz** [StreamController/StreamController#152]
**Description:** 
The Streamcontroller app's UI is entirely unresponsive. None of the buttons work, there are no hover effects, and the app cannot be closed through its interface. Despite background processes appearing to function correctly, the UI elements do not respond to any user interactions, making the app unusable. Initially, the app was installed and worked fine, but after a while, the UI stopped working. It is unclear if this issue was caused by an update or something else. This issue persists even after reinstalling the app or installing it from the latest GitHub version.

**Attempts to Resolve:**
1. Reinstalled the app - issue persists.
2. Installed the app from the latest GitHub repository - issue persists.

**Environment:**
- **Operating System:** Arch Linux
- **Desktop Environment:** KDE Plasma
- **Display Server:** X11

![image](https://github.com/StreamController/StreamController/assets/118930716/f16068b4-6620-4068-95fb-ff1b198a9eeb)

**Additional Notes:**
- The app needs to be forcefully killed to close it.
- Background processes seem to work as expected despite the UI being unresponsive.

**Comment by objz** [comment]
**Update:**
The app now looks transparent and doesn't load up at all. I'm not sure why this happened, but it has occurred suddenly.

![image](https://github.com/StreamController/StreamController/assets/118930716/5338abae-382e-47b1-b2c9-a65eab650c5e)

**Comment by Core447** [comment]
Thanks for the detailed report! Are you seeing any relevant errors in the console when launching the app? Is this issue appearing immediently, or after the app was active for some time? I'll try to reproduce this as soon as possible.

**Comment by objz** [comment]
So what I did was try to run the app through the Konsole using the Flatpak command. Shockingly, the app worked fine, but there were some errors that I dumped into `StreamController.log`. Then I tried launching it with the `.desktop` shortcut because I thought the error might have been resolved, but the app had the same issue as before.

I inspected the `.desktop` file and noticed that it has different launch flags. The command in the `.desktop` file was:

```sh
flatpak run --branch=master --arch=x86_64 --command=/app/bin/launch.sh com.core447.StreamController
```
[StreamController-HEAD.log](https://github.com/user-attachments/files/16074889/StreamController-HEAD.log)


The command I originally ran was:

```sh
flatpak run com.core447.StreamController
```
[StreamController.log](https://github.com/user-attachments/files/16074894/StreamController.log)


When I ran the command with the flags in the terminal, I still encountered some errors, but the app worked and was responding. I also dumped the logs from this new command into `StreamController-HEAD.log`.

I checked the `.desktop` file permissions and the environment, but they were fine. The issue persists when launching from the `.desktop` shortcut. So the error only occurs  when launching it from a desktop shortcut.

**Comment by objz** [comment]
I discovered that when I launch the app through the terminal, it works fine initially. However, when I press a button on the Streamdeck to assign something, the UI crashes.
[StreamController.log](https://github.com/user-attachments/files/16074962/StreamController.log)

**Comment by Core447** [comment]
Okay thanks for the logs. I'll check this as soon as I can. Can you maybe try it on Wayland, just to see if this is an X only thing?

**Comment by objz** [comment]
Same on Wayland

**Comment by Core447** [comment]
Ok, thanks for testing! It looks like some label get stored as a list which crashes the ui. Do you know where the label "Cococry" is coming from (an action or did you set it manually)?

Edit: Nvm it comes from the info action

**Comment by Core447** [comment]
Seems like this was/is a bug of the Media plugin that doesn't get catched by the app. It should be fixed now, can you please update the plugin, restart the app and try again? If you can't update the plugin because the app crashes first, please try closing all media players and try again.

Coming releases of the app will also catch this

**Comment by objz** [comment]
now it works thanks!

**Comment by Core447** [comment]
Nice! Thank you for your report!
