### ISSUE TITLE
Timeout option for a Button State

### ISSUE THREAD

**Issue by Danie10** [StreamController/StreamController#156]
**Describe the feature idea**
If I have say a button set for state 1 to show the time, and it's state 2 is set for the date, right now we toggle between those states. The idea is to set a timeout for state 2 so that pressing the button whilst time is shown, will briefly show state 2 (the date) for the timeout period, then revert back to state 1 (the default).

A timeout action may achieve this so that could have a value in seconds (or is ms better).

**Additional context**
So the button actions may be:
1. State 2
2. Timeout

This may of course not work for buttons with more than two states.

**Comment by Core447** [comment]
Nice idea! However, I prefer a more generic approch than a "Change state after timeout" action. This could again be something for the AdvancedActions plugin of @G4PLS (which isn't in the store yet), but adding this to the change state action should also be fine.

**Comment by Danie10** [comment]
I suppose, though, actually toggling is also not a major issue. My suggestion above is really for being super lazy and just pressing once instead of twice ;-)

Toggling still allows one to rotate through 2 or 3 or more states. The timeout suggestion here really only works for two states. I have another idea I'll log separately, which could be useful for displaying status on triggers.

**Comment by Core447** [comment]
What do you think of [16fc953](https://github.com/StreamController/DeckPlugin/commit/16fc953e3f554b963de79312241a0941265ef966) (it's already in the store)? It adds the timeout option directly to "Change State" allowing to go back after n seconds. We can also add this to "Change Page" if it's useful and feels good

**Comment by Danie10** [comment]
That is working perfectly thanks, and I see date is there also. So %a %d %b would show Mon 08 Jul for example. Putting the state delay only on state 1 always ensures it returns to state 1 even if 2 is active for some reason. But all working as I'd expect.

Just wondering is there any newline that we can insert to say have a line for weekday name then date below that. I tried \n but that did not work.

**Comment by Core447** [comment]
> That is working perfectly thanks, and I see date is there also. So %a %d %b would show Mon 08 Jul for example. Putting the state delay only on state 1 always ensures it returns to state 1 even if 2 is active for some reason. But all working as I'd expect.

Great!

> Just wondering is there any newline that we can insert to say have a line for weekday name then date below that. I tried \n but that did not work.

This is currently not possible, but I can add a line select option to the Date action and then you can use two of them

**Comment by Danie10** [comment]
OK thanks yes that should work as well then. Otherwise, the date gets a bit scrunched up and small if one wants to show say:

```
  Monday
8 Jul 2024
```

**Comment by Core447** [comment]
Yeah, the changes should already be available in the store

**Comment by Danie10** [comment]
Thanks working perfectly now!

![Date](https://github.com/StreamController/StreamController/assets/1153726/2523f1f4-d101-4b29-bb06-2f1da0bbf2d8)
