### ISSUE TITLE
BUG: Keys not cleared

### ISSUE THREAD

**Issue by Core447** [StreamController/StreamController#158]
**Describe the bug**
Removing a plugin doesn't clear controlled keys

**To Reproduce**
1. Install the clock plugin
2. Add an analog clock action
3. Uninstall the clock plugin

**Comment by gensyn** [comment]
Do you want the plugin to be removed from all keys it was previously assigned to? I found some code regarding that, but it was not being executed (`remove_from_pages:bool = False`). If I enable it, there are some errors in the code that break the execution and even if it would work, it would only clear the keys of the current page.
So what is the desired behavior?

**Comment by Core447** [comment]
The app should update all inputs (keys) that use actions from plugins that get uninstalled. This way old labels and images of actions no longer installed get cleared from the deck. So for example: If the "Digital Clock" action is on the deck and the "Clocks" plugin gets uninstalled we need to remove the label set by the action. Right now the key just freezes.

We could also remove the actions completely (I think this was done previously but broke with `1.5.0-beta.5`) and then update the keys.

**Comment by Core447** [comment]
Fixed with 54447643704ffd48e4c94f0a3bd3e44a78418826
