### ISSUE TITLE
BUG - Stream Deck + not being recognized

### ISSUE THREAD

**Issue by Frexium** [StreamController/StreamController#159]
**Describe the bug**
Hello, i am currently using your app on pop! os, with a Stream Deck + following a switch from Windows. I think i followed the downloading installation, but i do get errors when launching through the ``flatpak run com.core447.StreamController`` command. Errors are the following : 

``| ERROR    | __main__:quit_running:204 - org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable``
``| ERROR    | __main__:reset_all_decks:192 - Failed to reset deck, maybe it's already connected to another instance? Skipping...``

and a bit later : 

`` ERROR    | src.backend.DeckManagement.DeckManager:load_hardware_decks:89 - Failed to open deck. Maybe it's already connected to another instance?``

When i unplug and plug the deck again, it gives me the following : 

`` INFO     | src.backend.DeckManagement.DeckManager:on_connect:132 - Device /dev/bus/usb/001/013 with info: {'ID_MODEL_ID': '0084', 'ID_MODEL': 'Stream_Deck_Plus', 'ID_MODEL_FROM_DATABASE': '', 'ID_VENDOR': 'Elgato', 'ID_VENDOR_ID': '0fd9', 'ID_VENDOR_FROM_DATABASE': 'Elgato Systems GmbH', 'ID_USB_INTERFACES': ('030000',), 'ID_USB_CLASS_FROM_DATABASE': '', 'DEVNAME': '/dev/bus/usb/001/013', 'DEVTYPE': 'usb_device'} connected``

``Exception in thread USB Monitor:
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/app/lib/python3.11/site-packages/pyudev/monitor.py", line 544, in run
    self._callback(device)
  File "/app/lib/python3.11/site-packages/usbmonitor/__platform_specific_detectors/_linux_usb_detector.py", line 73, in __handle_device_event
    on_connect(device_id, device_info)
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckManager.py", line 137, in on_connect
    self.connect_new_decks()
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckManager.py", line 149, in connect_new_decks
    self.add_newly_connected_deck(deck)
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckManager.py", line 177, in add_newly_connected_deck
    deck_controller = DeckController(self, deck)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 333, in __init__
    deck.open()
  File "/app/lib/python3.11/site-packages/StreamDeck/Devices/StreamDeck.py", line 214, in open
    self.device.open()
  File "/app/lib/python3.11/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 372, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 223, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.``

**To Reproduce**
I sadly don't really know where i messed up, or if it's a problem with the deck.

**Screenshots**
![image](https://github.com/StreamController/StreamController/assets/41706570/fa1474b1-0aa3-4c82-a307-1976e52ddb53)
![image](https://github.com/StreamController/StreamController/assets/41706570/76bf23bf-f45e-441c-9f59-8143ce60ad1b)
![image](https://github.com/StreamController/StreamController/assets/41706570/01ebfb54-0846-4009-81ef-5241e91ee398)

If you need any more detail, i'll gladly provide more screenshots.

**Comment by Core447** [comment]
Most times this means the deck is controlled by some other app. Please also make sure that there's no other StreamController session opened. You can close all of them via `flatpak kill com.core447.StreamController`

**Comment by Frexium** [comment]
Hello again!
I tried what you told me, and it still doesn't seem to work.
The StreamDeck + just get into the standard "elgato phase" but doesn't go any further, and nothing is shown in the app.
I also still get the same errors.

**Comment by Core447** [comment]
Did you try [this](https://core447.com/streamcontroller/docs/latest/common_problems/#1-no-decks-found) (the udev rules)?

**Comment by Frexium** [comment]
No i didn't, and it was the solution to my problem, thank you very much, and sorry for the inconvenience!

**Comment by Core447** [comment]
No problem, I'm glad it's working now
