### ISSUE TITLE
No Streamdeck found on ZorinOS 17.1

### ISSUE THREAD

**Issue by CptWonderful** [StreamController/StreamController#162]
Installed via Zorin Store - Flatpack. 
Permissions seems to be right.

Error: No decks discovered

Do you need further information?

**Comment by Core447** [comment]
Have you already tried [this](https://core447.com/streamcontroller/docs/latest/common_problems/#1-no-decks-found)?

**Comment by CptWonderful** [comment]
> Have you already tried [this](https://core447.com/streamcontroller/docs/latest/common_problems/#1-no-decks-found)?

Did not see that Wiki... That solved my problem - Thanks!
