### ISSUE TITLE
Question: What additional arguments are available?

### ISSUE THREAD

**Issue by marvin1099** [StreamController/StreamController#165]
**Describe the bug**
At startup i like to add a script that runns the client in the backround,
how do i do that?
Btw im not on the flatpac,
the flatpac is a bit laggy,
i rather run with a venv.

**Comment by Core447** [comment]
You can use the -b argument to achieve this

**Comment by marvin1099** [comment]
got it are the arguments documented somewhere?
so far i only found:
```
usage: main.py [-h] [-b] [--devel] [--skip-load-hardware-decks] [--close-running] [--data DATA]
[--change-page SERIAL_NUMBER PAGE_NAME]
[app_args ...]

positional arguments:
app_args

options:
-h, --help            show this help message and exit
-b                    Open in background
--devel               Developer mode (disables auto update)
--skip-load-hardware-decks
Skips initilization/use of hardware decks
--close-running       Close running
--data DATA           Data path
--change-page SERIAL_NUMBER PAGE_NAME
Change the page for a device
```
by using:
`python main.py -h`
but this seems incomplete.
I just now seen `-b` is listed but is this all there is?
I mean for example `app_args` are not explained in any way.

**Comment by Core447** [comment]
> got it are the arguments documented somewhere?

Just in the help screen (`-h` or `--help`). `app_args` get passed to GTK, I would need to check what is available.

**Comment by marvin1099** [comment]
got it
