### ISSUE TITLE
Question: How to add a newline to a string

### ISSUE THREAD

**Issue by marvin1099** [StreamController/StreamController#166]
When using the clock on the streamdeck i would like to have:
%H:%m:%S\n%d.%m.%Y

Right now i have 2 clocks on one button,
one in the middle and one on the top 
that works but they are quite far apart,
if i can add a newline i can use one clock
and it will show this 
```
%H:%m:%S
%d.%m.%Y
```
centered and close together.

**Comment by marvin1099** [comment]
I found out it can be added if it gets pasted from a document or \n gets added in the page file.

**Comment by Core447** [comment]
You can also achieve this by using two date actions set to different lines (make sure to also set the action which controls the matching labels).


> I found out it can be added if it gets pasted from a document or \n gets added in the page file.

I need to check why this happens
