### ISSUE TITLE
It would be great if the outline on text could be changed

### ISSUE THREAD

**Issue by marvin1099** [StreamController/StreamController#168]
**Describe the feature idea**
When adding text to a button the text can be colored but the outline is always black,
so as i have asked in the title changing the outline of the text would be great.
I would be nice if color and thickness could be changed to make text easier to read on the stream deck.

**Comment by gensyn** [comment]
I created [a PR](https://github.com/StreamController/StreamController/pull/174) for this.

**Comment by Core447** [comment]
merged with e4373c471de01463856faf377eb209f7a4be1126

**Comment by marvin1099** [comment]
Thanks
