### ISSUE TITLE
Certain fonts cannot be selected via UI, but do work with StreamController

### ISSUE THREAD

**Issue by jonathanhirschman** [StreamController/StreamController#172]
**Describe the bug**
Certain fonts appear to be available when formatting a Label, but are not actually selected by the UI, and are not written to corresponding page config file. Manually editing the JSON file for the page *may* allow such fonts to be employed - there seems to be a visual change of some kind. This is for version 1.5.0-beta.6, tested on Ubuntu 24.04, default GNOME on X.

**To Reproduce**
1. Click on a blank button,
2. Enter a string for a label,
3. Click on the font selection button,
4. Select font from resulting dialog (for example, Work Sans Bold), either by double-clicking on the font name, or by single-clicking on the font name and then clicking on "Select",
5. A different font is actually selected (in this example, Work Sans Regular).

**Expected behavior**
Fonts should be selected correctly.

**Screenshots**
For example, selecting this font, shown here:

![image](https://github.com/user-attachments/assets/4dac210d-fd84-427a-a473-8cf57b83409a)

...actually selects Work Sans Regular, aka Work Sans, and produces this config snippet:
`"labels": {
                        "center": {
                            "text": "Test",
                            "font-family": "Work Sans",
                            "font-size": 18.0
                        }`

**Additional context**
The issue appears to have something to do with some fonts having more than two words in their name. For example, if the above snippet is manually modified to:

`"labels": {
                        "center": {
                            "text": "Test",
                            "font-family": "Work Sans SemiBold",
                            "font-size": 18.0
                        }`

..a different font is used after app restart, as shown here:

![image](https://github.com/user-attachments/assets/b8307325-bd7f-4df2-99f8-27491e0e1f89)

It isn't clear whether the correct font is being employed, but something different is:

![image](https://github.com/user-attachments/assets/0e5a5b67-ce92-4973-9dc5-d52d23117f40)

**Comment by Core447** [comment]
Should be fixed with bd7374647402bd59fbeb4581bd59cec7ca2a79fd.

**Comment by jonathanhirschman** [comment]
Thanks! StreamController is awesome!

**Comment by Core447** [comment]
> StreamController is awesome!

Thanks!
