### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by nosduco** [StreamController/StreamController#175]
**Describe the feature idea**

Could you distribute your package via the AUR?

**Additional context**

If unsure or don't want to maintain, I could write a PKGBUILD and upload it to the AUR and maintain it.

**Comment by Core447** [comment]
I'd like to have an AUR package, however, I'm currently not planning to add it, because the Flatpak allows easy publishing to all platforms. But if you're interested in publishing and maintaining it there, feel free to do so. Someone already wanted to do this, but I can't find the messages any more it's been quite some time since then.

**Comment by NeoMorfeo** [comment]
@nosduco I'm using Arch, so if you want a tester or some help, I could be your tester 😄

**Comment by nosduco** [comment]
I just wrote and published an initial package. The AUR doesn't contain all the required packages for the project so I couldn't write the PKGBUILD to install the packages to the system but rather install locally to the package without a virtualenv.

https://aur.archlinux.org/packages/streamcontroller

@NeoMorfeo Feel free to test, thanks :)

**Comment by NeoMorfeo** [comment]
Tested and works like a charm!! Thank you @nosduco !

**Comment by nosduco** [comment]
@Core447 If you're open to it I can make a PR to add this to the README. Or if you'd like to keep outside the ecosystem that is okay. I'll maintain it on the AUR.

**Comment by Core447** [comment]
First of all: Sorry for the huge delay. I'm not home atm.

The package looks really nice, great work! If you want, you can open a PR for the README, but please mention that the package is not official. But otherwise I can add it in the coming days.

**Comment by nosduco** [comment]
@Core447 No worries at all! 

Thank you, just went ahead and opened #188 

Let me know if that works for you or if you want something simpler. 

Thanks!

**Comment by Core447** [comment]
Merged #188, thank you! I also added this to the wiki

**Comment by Core447** [comment]
What do you think about using always the newest tag instead of the head for the aur package?

**Comment by nosduco** [comment]
@Core447 Replied to you on Discord but fixed the mentioned items. As for the tag, if you think pulling from `main` could get unstable then switching to versions/newest tag could be worth it.

Let me know and I can make that change!

**Comment by Core447** [comment]
> As for the tag, if you think pulling from `main` could get unstable then switching to versions/newest tag could be worth it.

Atm the main branch is not always very stable, so at least for the current non `-git` package, I would prefer the tag setup.

**Comment by Core447** [comment]
Gonna close this as we can chat on discord
