### ISSUE TITLE
Unable to run plugins with backends on Debian-derived systems using the default `/bin/sh`

### ISSUE THREAD

**Issue by pniedzielski** [StreamController/StreamController#192]
**Describe the bug**
When installed on a Debian (or presumably Ubuntu) system, which defaults to using the Dash shell rather than Bash, plugins with backends cannot be loaded.

**To Reproduce**
Steps to reproduce the behavior, run the following on a Debian system:
1. git clone https://github.com/Core447/StreamController
2. cd StreamController
3. python -m venv .venv
4. source .venv/bin/activate
5. pip install -r requirements.txt
6. python3 main.py
7. When prompted, install a plugin with a backend, such as the official OBS plugin, or [the Twitch plugin](https://github.com/ImDevinC/StreamControllerTwitchPlugin).
8. You will see log output of the following form, and the plugin will not be fully functional:

    2024-08-05 04:24:00.352 | INFO     | src.backend.PluginManager.PluginBase:launch_backend:519 - Launching backend: source /home/pniedzielski/.var/app/com.core447.StreamController/data/plugins/com_imdevinc_StreamControllerTwitchPlugin/.venv/bin/activate && python3 /home/pniedzielski/.var/app/com.core447.StreamController/data/plugins/com_imdevinc_StreamControllerTwitchPlugin/twitch_backend.py --port=34053
    /bin/sh: 1: source: not found

**Expected behavior**
Plugins should function correctly.

**Additional context**
This seems to be caused by a handful of lines [like this](https://github.com/StreamController/StreamController/blob/488a38c4e6f6135f5958207f12ec56d7ea281f57/src/backend/PluginManager/ActionBase.py#L448), which try to invoke the Bash `source` primitive.  This is fed to `subprocess.Popen(..., shell=True, ...)`, which runs the command with `/bin/sh`, the system POSIX shell.  `source` is a Bash-ism, and only works if `/bin/sh` is Bash.  On Debian systems, `/bin/sh` is a leaner POSIX-compatible shell called Dash, so this command fails.  Changing this command to run Bash fixes this issue.

It looks like there's a little more room for error handling here as well, as the plugins do not complain that they cannot run their backend on this failure.

**Comment by pniedzielski** [comment]
I will prepare a PR with these changes.

**Comment by Core447** [comment]
Thanks for fixing this!
