### ISSUE TITLE
BUG: set_background not working when action loads/on_update

### ISSUE THREAD

**Issue by G4PLS** [StreamController/StreamController#202]
**Describe the bug**
Im using `set_background` to set the background of a button, this works but only after I press the button once
It also does not change the Background color in the Background section of the Action.

```py
def on_ready(self):
    self.load_settings()
    self.set_background_color([101, 124, 194, 255])
    
def on_update(self):
    self.set_background_color([101, 124, 194, 255])

def on_key_down(self):
    self.on_update()
```

**To Reproduce**
The Methods above should be the bare minimum to reproduce this, when this does not work the "RecordChapterAction" of [OBSController](https://github.com/G4PLS/OBSController) currently has this behaviour

**Expected behavior**
The Background color should get changed on the Button.
It should also update the Background color in the Background section

**Screenshots**
Mismatch between Background section and actual button background
![image](https://github.com/user-attachments/assets/5005f845-8d80-4509-af3e-2177e67ba5e0)

Directly after the action loads:
![image](https://github.com/user-attachments/assets/029e23d6-466f-472d-9b7b-bb291c19d59b)

**Comment by G4PLS** [comment]
When you do set_background color in on_ready or on_update it sets the color correctly, but afterwards it runs code to use the background color selected by the background color selector. So the order of operation is wrong from these functions

This could fix that:

Add a new field to the Actions section of a button to enable background overriding.

The way it is implemented at the moment you cant set the background color programmatically because it gets overriden with the color of the background chooser
This would bring the total of buttons up to three but i personally think its worth it

BC stands for Background Color
![image](https://github.com/user-attachments/assets/267fa684-b999-4aad-bb10-d664d766e6a7)
Only 1 Action should be able to set the background color, by default this should be off
When enabled it blocks the use of the normal background color

**Comment by G4PLS** [comment]
@Core447 just wanted to bump this issue again as its quite the annoyance when developing plugins
You always have to use on_tick when wanting to set the background color

**Comment by Core447** [comment]
It's nearly fixed - I'll include the change in the .7 release

**Comment by Core447** [comment]
added with 1c06967fff52dfd18261862432f7ee4d4cecc13f - Can you please check if this is what you intended?

**Comment by G4PLS** [comment]
I think it would make sense if the first action added to a key has it enabled by default in the same way the Icon permission is handled.

In the other ways its behaving exactly like I imagined. Background color gets set immediately when changing permissions and the background color as well as icons can be set at startup instantly without having to use on_tick.

Overall very happy with the change and I personally think its a great addition to the app (Biased ofc).
I also think this now makes on_update useful to use and does exactly what it should do in its entirety.

**Comment by Core447** [comment]
> I think it would make sense if the first action added to a key has it enabled by default in the same way the Icon permission is handled.

Added with 5be433f0ec8bcc10aef89ec5f037d0c4a118c4ec
