### ISSUE TITLE
BUG: StreamController fails to launch

### ISSUE THREAD

**Issue by vguttmann** [StreamController/StreamController#225]
**Describe the bug**
StreamController fails to launch out of the blue with the error message `2024-09-07 13:48:02.642 | ERROR    | __main__:quit_running:204 - org.freedesktop.DBus.Error.ServiceUnknown: The name com.core447.StreamController was not provided by any .service files

**To Reproduce**
1. Something happens to the system (haunted?)
2. Launch StreamController from the terminal to see debug messages with `flatpak run com.core447.StreamController`
3. It throws the error message2024-09-07 13:48:02.642 | ERROR    | __main__:quit_running:204 - org.freedesktop.DBus.Error.ServiceUnknown: The name com.core447.StreamController was not provided by any .service files

**Expected behavior**
StreamController launches

**Screenshots**
![Screenshot from 2024-09-07 13-52-12](https://github.com/user-attachments/assets/dbcfae90-64d5-4f27-be32-9963e7a16459)

**Additional context**
StreamController did not start at startup like it was supposed to either, and launching via Shortcuts has the same effect.
System: Ubuntu 22.04
Reinstall of StreamController was attempted, but produced the same result

**Comment by ImDevinC** [comment]
@vguttmann this error shouldn't cause this issue, are you able to provide the full log please?

**Comment by vguttmann** [comment]
Well... After a few more system reboots unrelated to this, it works again ¯\_(ツ)_/¯Is there a location where logs persist across system reboots?On 9 Sept 2024 20:47, Devin Collins ***@***.***> wrote:
@vguttmann this error shouldn't cause this issue, are you able to provide the full log please?

**Comment by ImDevinC** [comment]
~Logs are not currently stored anywhere locally by default~ (This was wrong, see the response below)

**Comment by Core447** [comment]
You can find the logs under `~/.var/app/com.core447.StreamController/data/logs/logs.log`, but unfortunately not all errors are getting written into this file atm
