### ISSUE TITLE
BUG Page autoswitching does not work in Ubuntu XFCE4 X11

### ISSUE THREAD

**Issue by zeridon** [StreamController/StreamController#229]
**Describe the bug**
Neither on master nor on 1.5.0-beta6 page autoswitching works when used on Ubuntu (24.04.1), XFCE4 (4.18), X11 (xserver-xorg - 1:7.7+23ubuntu3)

**To Reproduce**
Create a page for autoswitching (in my case for MS teams webapp)
Add matcher on 'teams'
Check that single window is matched

Switch to MS Teams web app

Page is not switched

**Expected behavior**
Page is automatically switched

**Screenshots**
Attached sanitized page
[Teams.json](https://github.com/user-attachments/files/16993324/Teams.json)

**Comment by zeridon** [comment]
More Info:

Install type: python venv

Tried also with flatpack

**Comment by zeridon** [comment]
After some debugging maybe a solution is found.

After tracing `src/backend/WindowGrabber/Integrations/X11.py` with judicios `log.info()` and manually following the path the following is evident:

 * `self.start_active_window_change_thread()` is executed
 * `self.x11.get_active_window()` is executed on tight loop (maybe 0.2 s is a bit fast)
 * `self._run_command(["xprop", "-root", "_NET_ACTIVE_WINDOW"])` is executed
 * * this returns `_NET_ACTIVE_WINDOW(WINDOW): window id # 0x52fe9d4, 0x0`
 * window_id to be inspected later on is: `window_id = split[-1]` which in this case is `0x0`
 * `0x0` stops the processing (in other calls) so no window change is detected.

The simplistic fix is to set the window_id to `split[-1]` which works for the moment (for me). Will work on a more sensible patch.

**Comment by Core447** [comment]
> The simplistic fix is to set the window_id to `split[-1]`

Isn't this already the case in line [101](https://github.com/StreamController/StreamController/blob/c8962b32bd1225116877b31ab7fd7932baf66a5f/src/backend/WindowGrabber/Integrations/X11.py#L101)?

**Comment by zeridon** [comment]
Sory ... typo. Meant to say `split[-2]`
