### ISSUE TITLE
BUG - v1.5.0-beta.6 - OS plugins missing "Run Command", "memory graph", "cpu graph", "click", "Delay", "Move XY" sub-commands

### ISSUE THREAD

**Issue by fliptoback** [StreamController/StreamController#235]
**Describe the bug**
Already installed with the latest OS plugins - but the menu for "OS" is missing a bunch of sub-commands as described in title above.

**To Reproduce**
1. Go to sidebar
2. Click on OS

**Expected behavior**
Am expecting to see a more complete sub-commands

**Screenshots**
Please see below
![Screenshot_20240921_143749](https://github.com/user-attachments/assets/c44aba07-8382-496a-a3e9-87cb1e8d112e)

**Comment by fliptoback** [comment]
I managed to solve the issue - I was using the flatpak version and even though via Flatseal, the "Filesystem=host-os" checkbutton is selected, but I am still missing these sub-commands.

So I uninstall the flatpak, reinstall it, and then re-enable the host-os checkbutton and viola those sub-commands are back.

Maybe just a small glitch earlier.

Thanks. it is working now.

**Comment by Core447** [comment]
Still weird. I had to update the OS plugin a few times in the last days, hopefully this didn't break something. But normally if an update fails the whole plugin gets hidden, not just some actions.
