### ISSUE TITLE
"The chosen image dosen't seem to have RGB colour channels", how can I fix this? I've tried converting in GIMP but I have no idea how ot use GIMP.

### ISSUE THREAD

**Issue by CharlieRich10** [StreamController/StreamController#247]
When I add my image to my stream deck as a background image on any page, I get an error saying "The chosen image doesn't seem to have RGB colour channels, please convert it in a app like GIMP"

1. Download the image: https://wallhaven.cc/w/yxp1pk
2. Click on try adding it as a background image to a page
3. See error

Any help resolving this issue is greatly appreciated.

**Comment by Core447** [comment]
Fixed with fff11058ac257cf81c5791173d9468bccf5a898a - But it will take some time until it's available on Flathub. In the meantime please convert the image using `convert image.jpg -colorspace rgb image.jpg` before adding it to the app.
