### ISSUE TITLE
using system clipbaord

### ISSUE THREAD

**Issue by rastarr** [StreamController/StreamController#249]
I can't start without first saying this project is simply on par with the Elgato software. I moved from a long term macOS user and being able to use my StreamDeck on Linux was such a pain, up until StreamController. Kudos to all the devs, you rock

OK I mainly use my StreamDeck for the Write Text feature, in a support role.

**Describe the feature idea**
using the system clipboard within Write Text area to paste the clipboard contents.
Is there some way I can use a system variable or bash insert like {{clipboard}} within the Write Text field that inserts the clipboard?

![stream](https://github.com/user-attachments/assets/94632afb-b47c-44f5-b23e-1467af90a4a6)

**Comment by Core447** [comment]
You can achieve this with the following action setup:
1. Write text set to "Please click the link below and reset your password"
2. Hotkey set to "CTRL + V"
3. Write text set to "Thank you..."

**Comment by rastarr** [comment]
@Core447 
Ahh ha, now I get it and thank you. works like a charm.
