### ISSUE TITLE
BUG Top row and right-most column buttons don't work on Deck XL at first

### ISSUE THREAD

**Issue by StelardActek** [StreamController/StreamController#255]
**Describe the bug**
Top row and right-most column buttons don't work on Deck XL at first. They start working after other buttons have been pressed.

**To Reproduce**
1. Connect a Stream Deck XL
2. Start StreamController
3. Assign an action to any button in the top row or right-most column
4. Restart StreamController and test if the action works

**Expected behavior**
The icon on the pushed button should shrink temporarily as visual feedback, and the action should fire.

**Observed behavior**
No visual feedback, the action does not fire. However, after pressing any button in the normal Stream Deck range -- it doesn't even have to have an icon or action associated with it -- the full range of buttons becomes active.

**Screenshots**
n/a

**Additional context**
Version: 1.5.0-beta.6

**Comment by Core447** [comment]
Ok, that's weird. The problem is that I don't have an XL for debugging this...

**Comment by StelardActek** [comment]
On further testing this may have fixed itself. I can only check it once a boot so it's a pain, but the only thing that's changed is I downloaded some icon packs and applied an icon to the button in the top right, where previously it was just a label and the default icon for the OS Run Command action.

I'll keep an eye on it and close this if it keeps working.

**Comment by Core447** [comment]
> I'll keep an eye on it and close this if it keeps working.

Alright!

**Comment by StelardActek** [comment]
Yeah, this seems to have stopped happening. No idea what could have caused it.
