### ISSUE TITLE
Stream Deck Neo: strip and physical change page button support

### ISSUE THREAD

**Issue by DavideGhisalberti** [StreamController/StreamController#270]
**Describe the feature idea**
Stream Deck Neo has an additional strip used to display under the two rows of buttons, and two capacitive keys to handle (for example) page navigation. They should be supported by StreamController to complete the support for this device

**Comment by Core447** [comment]
I fully agree, however, I'm gonna close this issue, as we already have #141 tracking the Neo

**Comment by DavideGhisalberti** [comment]
Sorry, thank you! I thought the other issue was tracking only the first support

**Comment by Core447** [comment]
> Sorry, thank you! I thought the other issue was tracking only the first support

Np
