### ISSUE TITLE
BUG[PRE BETA 7]: Cant set labels in on_ready and on_update

### ISSUE THREAD

**Issue by G4PLS** [StreamController/StreamController#273]
**Describe the bug**
I cant set the labels anymore in on_ready and on_update, i get the following error: `Seems like you're calling this method before the action is ready`

Even though this gets displayed the labels are set, so im rather confused why this is happening

**To Reproduce**
Just have any `set_label` method in your on_ready or on_update. This for some reason also only happens with my Audio Plugin, havent tested with other Plugins

**Expected behavior**
Label should be able to be set at least in on_update. It should be able to be set in on_ready aswell as on_ready in my opinion means that the action is now ready

**Comment by Core447** [comment]
I only had this problem using `on_update` not `on_ready`, but it should now be fixed with a09875562f509c417ab2c18bdd474ba74c5527a0

**Comment by G4PLS** [comment]
Just tested it on the dev branch and the error is gone!
