### ISSUE TITLE
Was 1.5.0-beta.7 tag updated and force pushed to GitHub and point to a different commit?

### ISSUE THREAD

**Issue by sifmelcara** [StreamController/StreamController#279]
Hello! I noticed that a new 1.5.0-beta.7 release was made and overwrite the old 1.5.0-beta.7 release, and the git tag now points to a newer, different commit in dev branch.

When I try `git fetch --tags` to update my local copy, I get this error:
```
$ git fetch origin --tags
From https://github.com/StreamController/StreamController
 ! [rejected]        1.5.0-beta.7 -> 1.5.0-beta.7  (would clobber existing tag)
```

Nixpkgs build is also broken because of this, I understand that the tags are just "prerelease" tags so maybe we shouldn't expect it to be consistent, and we can workaround it if needed. Just want to bring it up here in case it's a accident or misconfiguration

Thanks!

**Comment by Core447** [comment]
Yes, I updated the 1.5.0-beta.7 pre-release tag (and release) to include important fixes. 

> Nixpkgs build is also broken because of this

Damn, that's annoying, however, as you said it was a pre-release and never meant to be used in production.

Sorry for the inconvenience. I should have been clearer about not using the tag for packaging.

Edit: I'll merge the current state of `dev` + #277 into `main` and then update the tag a last time and set it to a final release.

**Comment by sifmelcara** [comment]
Thanks, that helps!
