### ISSUE TITLE
Album art not working on spotify

### ISSUE THREAD

**Issue by youpie** [StreamController/StreamController#29]
When using the media info tile and enabling the 'show thumbnail of currently playing song' option. It does not work for spotify. Interestingly, it does work for spotify web on firefox.

I use gnome on wayland and the spotify flatpak

![image](https://github.com/StreamController/StreamController/assets/37704067/0e725f89-6109-4818-a8a7-28c2c36388f2)
When using spotify web

![image](https://github.com/StreamController/StreamController/assets/37704067/416277e3-e06c-40ed-97c8-c016e2c2496f)
When using spotify app

**Comment by oparada1988** [comment]
open the issue in the plugin repo: https://github.com/StreamController/MediaPlugin

**Comment by youpie** [comment]
> open the issue in the plugin repo: https://github.com/StreamController/MediaPlugin

Apologies, will do!
