### ISSUE TITLE
Feature Request: Export

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#40]
Hello, I would love to be able to export a streamdeck layout to a JSON/other file, so I can manually edit and import them to my other streamdecks; I have multiple decks, which all require an almost identical layout with only some minor argument adjustments for the scripts they run.

**Comment by Core447** [comment]
This will be added soon, in the meantime you can just copy the files manually from/within `~/.var/app/com.core447.StreamController/data/pages`

**Comment by v4u6h4n** [comment]
@Core447

Oh great, yeah that looks easy enough :-)

**Comment by Core447** [comment]
Implemented with 303dd856321b9db23b86190fec8b36241bfc631c

**Comment by v4u6h4n** [comment]
Oh, would it be possible for exporting all pages into a single JSON? It just simplifies batch replace operations, like updating a script argument, colour hex, etc.

**Comment by Core447** [comment]
Yes, I can add this. For now you can just manually edit the pages in `~/.var/app/com.core447.StreamController/data/pages`

**Comment by Core447** [comment]
Added in 638ccc02b529e9889152e05624880f3e6e3bdddc

**Comment by v4u6h4n** [comment]
~~Alright just had a chance to update, I can't see the export option. Is it still in the same menu as the import? Also, not sure if it's related or not, but I'm seeing the same reversion of the streamdeck names to being limited to only 'Streamdeck Mini 1` and 'Streamdeck Mini 2` again.~~

UPDATE: Don't know what the issue was, but fixed after a reboot. Export looks great, thanks!

**Comment by Core447** [comment]
Great! I have no idea why the naming problem only appears sometimes.

**Comment by v4u6h4n** [comment]
Tested the import for my 60k line export and it worked like a charm ;-)

**Comment by Core447** [comment]
Nice. All of the new import/export stuff will be available in the flatpak with the next release.
