### ISSUE TITLE
Doesn't work after waking up from system suspend

### ISSUE THREAD

**Issue by LordManhattan** [StreamController/StreamController#41]
App/service stops working after a system suspend. Current solution is to kill the app and launch it again. 

Software specs: 

- OS: Fedora 39
- DE: Gnome 45.5
- Kernel: 6.7.11-200.fc39.x86_64

**Comment by Core447** [comment]
This is a problem of the library we're using for the communication. The issue can be found [here](https://github.com/abcminiuser/python-elgato-streamdeck/issues/78). I will try to find a workaround in the next days

**Comment by mikeriley** [comment]
Seems this related python-elgato-streamdeck issue was resolved [here](https://github.com/timothycrosley/streamdeck-ui/issues/4). Looking forward to the fix being patched into StreamController, as I find its interface nicer and more user friendly than python-elgato-streamdeck. Keep up the good work.

**Comment by Core447** [comment]
Should be fixed with 471724159bdb9ae9b7ea17d93817a04355a24136. I'll close this issue if the fix is available on Flathub.

**Comment by mikeriley** [comment]
In the meantime, I slapped together a quick bash script that runs when the computer wakes, killing the existing StreamController PID and restarts the app. Currently, the GUI shows when running and while I considered including specific desktop parameters to hide it, I left it displayed by default for now to remind me to stop using the script once the [commit](https://github.com/StreamController/StreamController/commit/471724159bdb9ae9b7ea17d93817a04355a24136) has been deployed. Other StreamController users might find this stop-gap band-aid useful as well:

```
#!/bin/bash
# Get the process ID associated with StreamControlle
pid=$(pgrep -f "StreamControlle")

if [ -z "$pid" ]; then
    echo "StreamController app not running."
    exit 1
fi

# Kill the process
kill "$pid"
echo "Killed StreamController process with PID $pid."

# Restart StreamController and run in the background.
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/launch.sh com.core447.StreamController >/dev/null 2>&1 &
echo "Restarted StreamController app."
```

**Comment by mikeriley** [comment]
FYI - Just received the latest build via my flatpak distro but it fails to execute with the following error:

  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ ['flatpak-spawn --host ', 'xprop', '-root', '_NET_ACTIVE_WINDOW']
    │    └ <function Popen._execute_child at 0x7fad6052cd60>
    └ <Popen: returncode: 255 args: ['flatpak-spawn --host ', 'xprop', '-root', '_...>
  File "/usr/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ 'flatpak-spawn --host '
          │                    │          └ 'No such file or directory'
          │                    └ 2
          └ <class 'OSError'>

**Comment by Core447** [comment]
@mikeriley 
Are you on X? There's currently a bug preventing the launch on X outside of Gnome. This will be solved soon. I'm sorry for the inconvenience.

**Comment by mikeriley** [comment]
@Core447  - yes, that's it exactly. No worries. I'll sit tight until the next release and confirm working once tested. Thanks for your prompt response!

**Comment by mikeriley** [comment]
Just grabbed the latest flatpak update and the new version works perfectly, restarting automatically after sleep/suspend. Awesome job. Keep up the great work!
