### ISSUE TITLE
Feature Request: SVG support

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#42]
Hey, SVG support would be nice; I usually make minor adjustments to icons I use, and keeping everything in SVG makes things a lot easier.

**Comment by Core447** [comment]
Implemented with c3a2820e663ca5d8b86852b9e421ec7d49eaef0a. I'll close this issue when it's available on Flathub.

**Comment by v4u6h4n** [comment]
Thanks :-)
