### ISSUE TITLE
StreamDeck plus support

### ISSUE THREAD

**Issue by NeoMorfeo** [StreamController/StreamController#43]
It will be great to have this support, in the streamdeck-ui is partially supported, the lib it uses has full support... it is possible to help to support dials and touch screen? what will be required?
The application currently doesn't even detect my deck.

Thanks!

**Comment by Core447** [comment]
I don't have a Stream Deck plus, but if I have some time I can write a fake deck for it. But as far as I know the buttons should already work, just not the dials. Maybe [this](https://github.com/StreamController/StreamController/issues/31#issuecomment-2053628819) will help you get the buttons to work.

**Comment by NeoMorfeo** [comment]
Thank you for that! Would be great. That fake deck is possible to fit with the dials and touchscreen? Is there any documentation?

I have test the udev rules, and with streamdeck-ui works fine. I'll try to compile this project by my self and debug it I will share results

**Comment by Core447** [comment]
Thanks! No the current fake deck only has the buttons. But I'll try to change that so that I can test the dials when I'm adding support for the plus

**Comment by NeoMorfeo** [comment]
Ok! Let me know if you need to test it with a real device 💪

**Comment by Core447** [comment]
I'll get back to you when I start adding support for it. For now, though, it's not a priority

**Comment by mboelen** [comment]
Another possible tester reporting. Got also the Stream Deck + and would be very excited to add actions to those dials. Same showing some information on the mini-display.

**Comment by Core447** [comment]
> Another possible tester reporting. Got also the Stream Deck + and would be very excited to add actions to those dials. Same showing some information on the mini-display.

Great.

The current state of the SD plus support (stream-deck-plus branch): You can add actions to swipe left and swipe right on the touch screen. Most big changes for the dials are also finished. I still need to add full dial support, fix a ton of bugs and implement the coming state management to the screen and dials.

**Comment by LogicalUnit** [comment]
@Core447 StreamDeck+ user reporting for testing! 

I've been using the streamdeck-linux-gui project which supports the 8 regular buttons on my device -- awesome! However the developer there has stated that the touchscreen and rotary buttons would be too much work in that project. I would love to see touchscreen and rotary buttons working as well -- especially to control my Elgato Key Light!

**Comment by Core447** [comment]
@LogicalUnit When the plus support is finished, I can write an official Key Light plugin that you can use

**Comment by v4u6h4n** [comment]
@Core447 Literally bought one yesterday so that's good news lol

**Comment by GerardWassink** [comment]
> It will be great to have this support, in the streamdeck-ui is partially supported, the lib it uses has full support... it is possible to help to support dials and touch screen? what will be required? The application currently doesn't even detect my deck.
> 
> Thanks!

Same here, SD Plus not recognized.
I'd love to see it working like I used it on Windows for OBS. I switched to Pop!_OS recently and installed OBS there. It would very much help to have the SD + supported here also!
Gerard

**Comment by Core447** [comment]
SD Plus support will come soon, most of the heavy lifting is already done.

> Same here, SD Plus not recognized.

The normal buttons are already functional for the Plus, can you please try [this](https://streamcontroller.github.io/docs/latest/common_problems/?h=comm#1-no-decks-found) fix?

**Comment by GerardWassink** [comment]
> SD Plus support will come soon, most of the heavy lifting is already done.
> 
> > Same here, SD Plus not recognized.
> 
> The normal buttons are already functional for the Plus, can you please try [this](https://streamcontroller.github.io/docs/latest/common_problems/?h=comm#1-no-decks-found) fix?

Forgot to mention:
- using Pop!_OS 22.04 LTS
- Streamcontroller 1.5.0-beta.4

I have applied this fix, thanks.
Deck is now recognized as Stream Deck +
It keeps functioning after I close the app.

Still trying to set it up. I have to investigate the way it works I guess.

Thanks so far,

**Comment by GerardWassink** [comment]
> SD Plus support will come soon, most of the heavy lifting is already done.
> 
> > Same here, SD Plus not recognized.
> 
> The normal buttons are already functional for the Plus, can you please try [this](https://streamcontroller.github.io/docs/latest/common_problems/?h=comm#1-no-decks-found) fix?

In my earlier answer I was a little bit too quick. Streamcontroller did quit after a while when I closed the UI.
I then applied the second fix (run in background) and it seems to keep running so far.

**Comment by oparada1988** [comment]
> @LogicalUnit When the plus support is finished, I can write an official Key Light plugin that you can use

ive actually been looking into getting one of these, a neewer light plugin would be awesome as well!( got two of these)

**Comment by GerardWassink** [comment]
> SD Plus support will come soon, most of the heavy lifting is already done.
> 
> > Same here, SD Plus not recognized.
> 
> The normal buttons are already functional for the Plus, can you please try [this](https://streamcontroller.github.io/docs/latest/common_problems/?h=comm#1-no-decks-found) fix?

Today I tried Streamcontroller again. Sorry to say that Stream Deck + was again not recognized. I applied the same fix again, despite my thinking that it will not change anything the second time we run it. Also checked the settings/applications, Streamcontroller is still set to run in background.

Any help would be appreciated.

**Comment by Core447** [comment]
> Today I tried Streamcontroller again. Sorry to say that Stream Deck + was again not recognized. I applied the same fix again, despite my thinking that it will not change anything the second time we run it. Also checked the settings/applications, Streamcontroller is still set to run in background.\n\nAny help would be appreciated.

Can you check that you don't have any other app for the Stream Deck running (in auto start)?

**Comment by GerardWassink** [comment]
> > Today I tried Streamcontroller again. Sorry to say that Stream Deck + was again not recognized. I applied the same fix again, despite my thinking that it will not change anything the second time we run it. Also checked the settings/applications, Streamcontroller is still set to run in background.\n\nAny help would be appreciated.
> 
> Can you check that you don't have any other app for the Stream Deck running (in auto start)?

Nope:

![Screenshot from 2024-06-09 18-20-56](https://github.com/StreamController/StreamController/assets/14130149/98e1be6c-6f41-4b14-b328-ce6135ae7345)

**Comment by Core447** [comment]
> Nope:

Can you please try if one of the examples of [python-elgato-streamdeck](https://github.com/abcminiuser/python-elgato-streamdeck) works and detects the deck when SC doesn't, if you feel comfortable doing so? You can find them under `src` on the gh

**Comment by GerardWassink** [comment]
> > Nope:
> 
> Can you please try if one of the examples of [python-elgato-streamdeck](https://github.com/abcminiuser/python-elgato-streamdeck) works and detects the deck when SC doesn't, if you feel comfortable doing so? You can find them under `src` on the gh

Will try that tomorrow. (CET)

**Comment by GerardWassink** [comment]
> > Nope:
> 
> Can you please try if one of the examples of [python-elgato-streamdeck](https://github.com/abcminiuser/python-elgato-streamdeck) works and detects the deck when SC doesn't, if you feel comfortable doing so? You can find them under `src` on the gh

I downloaded the Streamcontroller repository and tried the main.py
This results in errors:

gerard@gryphon: /prg/python/StreamController-main$ python3 main.py
Traceback (most recent call last):
  File "/home/gerard/prg/python/StreamController-main/main.py", line 16, in <module>
    import setproctitle
ModuleNotFoundError: No module named 'setproctitle'
gerard@gryphon: /prg/python/StreamController-main$ 

Also tried the ./src/app.py and also missing stuff.

Python is an long, long time ago for me.
How do I start it (and what module) ?

**Comment by Core447** [comment]
> I downloaded the Streamcontroller repository and tried the main.py
> This results in errors:

You're probably missing some packages in your environment. You can follow the installation instructions from the [wiki](https://streamcontroller.github.io/docs/latest/installation/#github), also look for any errors during `pip install -r requirements.txt`. However, your PopOS will probably have a too old version of libadwaita installed. This is why I recommend to use the examples of the library I use for the decks: [python-elgato-streamdeck](https://github.com/abcminiuser/python-elgato-streamdeck)

Edit: Still, it's weird that it worked once

**Comment by GerardWassink** [comment]
> > I downloaded the Streamcontroller repository and tried the main.py
> > This results in errors:
> 
> You're probably missing some packages in your environment. You can follow the installation instructions from the [wiki](https://streamcontroller.github.io/docs/latest/installation/#github), also look for any errors during `pip install -r requirements.txt`. However, your PopOS will probably have a too old version of libadwaita installed. This is why I recommend to use the examples of the library I use for the decks: [python-elgato-streamdeck](https://github.com/abcminiuser/python-elgato-streamdeck)
> 
> Edit: Still, it's weird that it worked once

This is getting a bit too convoluted for my liking.

Perhaps a reason for it having worked, and now stopped, could be found in the fact that I, in between the two tries, experimented a bit with Qjackctl and jack_mixer. Both audio applications that lean on ports.... ?

**Comment by Core447** [comment]
> This is getting a bit too convoluted for my liking.

Just one more thing: I tested `ps alx | grep stream` and it doesn't print my active instance. Can you please run:
1. `flatpak kill com.core447.StreamController`
2. `flatpak run com.core447.StreamController`

?

**Comment by GerardWassink** [comment]
> > This is getting a bit too convoluted for my liking.
> 
> Just one more thing: I tested `ps alx | grep stream` and it doesn't print my active instance. Can you please run:
> 
>     1. `flatpak kill com.core447.StreamController`
> 
>     2. `flatpak run com.core447.StreamController`
> 
> 
> ?

Tried that and it did connect now, also functioning but it spits out a lot of messages, see images below:

![Screenshot from 2024-06-11 07-36-20](https://github.com/StreamController/StreamController/assets/14130149/f83c635f-1f09-457f-8134-2c6855061950)

![Screenshot from 2024-06-11 07-39-56](https://github.com/StreamController/StreamController/assets/14130149/4a803ddd-612d-444e-872a-106e1067e350)

![Screenshot from 2024-06-11 07-43-10](https://github.com/StreamController/StreamController/assets/14130149/33d476d9-54b6-4a46-ab79-e8a97bee7b2e)

**Comment by GerardWassink** [comment]
> > This is getting a bit too convoluted for my liking.
> 
> Just one more thing: I tested `ps alx | grep stream` and it doesn't print my active instance. Can you please run:
> 
>     1. `flatpak kill com.core447.StreamController`
> 
>     2. `flatpak run com.core447.StreamController`
> 
> 
> ?

Also tried to capture the log. I also see these messages:

_launch backend
backend launched

callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7e71c990cc40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x57afc52436b0)>>
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7e71c990cc40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x57afc52436b0)>>
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7e71c990cc40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x57afc52436b0)>>
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7e71c990cc40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x57afc52436b0)>>_

Also see this logfile:

[StreamController.log](https://github.com/user-attachments/files/15782856/StreamController.log)

**Comment by GerardWassink** [comment]
Perhaps I found a clue...
When I restart my system, StreamController occurs twice in the Startup applications.
I removed one of them and rebooted. Again, two occurrences.
Is that supposed to be like that?

![Screenshot from 2024-06-11 11-28-59](https://github.com/StreamController/StreamController/assets/14130149/c4b67fec-d1b9-40fb-a48c-98ba64a7689c)

**Comment by Core447** [comment]
> Is that supposed to be like that?

No, can you remove both and try again?

If this doesn't help, you can also disable the autostart in the app settings:
![image](https://github.com/StreamController/StreamController/assets/100139110/46b0bb71-4b9c-40c8-8b4b-442e3ebf81a1)
This way the app should no longer add new entries.

You're problem probably occurs because StreamController gets launched twice, preventing one instance from accessing the decks.

**Comment by GerardWassink** [comment]
Okay, only one left and it's working now:

![Screenshot from 2024-06-11 16-08-11](https://github.com/StreamController/StreamController/assets/14130149/62cd9a21-3bba-4540-b423-83e19b410000)

I installed using flatpak in Pop!_OS. Is there some documentation about how to install icon sets?

Found this directory: /home/gerard/.var/app/com.core447.StreamController/data/icons
Do I simply create directories there per icon set?

**Comment by Core447** [comment]
> Okay, only one left and it's working now:

Great!



> I installed using flatpak in Pop!_OS. Is there some documentation about how to install icon sets?
> 
> Found this directory: /home/gerard/.var/app/com.core447.StreamController/data/icons Do I simply create directories there per icon set?

Unfortunately this is not yet documented. I recommend you to install one of the icon packs from the store and and apply the file scheme to your own icon packs. However, if you just want to add some icons for your personal use without the intention to publish them as a pack, I would recommend you to just use the "Custom Assets" section of the asset chooser, where you can simply drag and drop your icons right into the app.

If you have any other questions or bug reports, please open a new discussion or issue on github or join the [Discord](https://discord.gg/MSyHM8TN3u) server.

**Comment by Core447** [comment]
Support for the SD+ is now available.

**Comment by LogicalUnit** [comment]
Any movement on the Elgato Key Light plugin?

**Comment by GerardWassink** [comment]
> Any movement on the Elgato Key Light plugin?

Second that!

**Comment by Core447** [comment]
> Any movement on the Elgato Key Light plugin?

No, not yet as this isn't a priority right now for me. But maybe someone else wants to do it until/before I have time for it.
