### ISSUE TITLE
Cli Button Overide/Replace

### ISSUE THREAD

**Issue by Data-007** [StreamController/StreamController#47]
Data from streamdeck-linux-gui
On discord we spoke about this, you advised something about applying a custom action.
When doing OS->Run command you have a icon displayed like the cli icon common in Linux.
I would like an action to disable this icon. And either display an icon like all the other keys where user chooses,
or  have it blank allowing the display icon text to distinguish icons function.

At present I find no way of doing ether of these, the only option is to make the icon size 0,
this is remembered when the app is running, however on computer restart the icon size is not remembered.

**Comment by Core447** [comment]
For now you can just choose a fully transparent image as a custom icon. You can download and use the one between the following lines:

-----
![alpha](https://github.com/StreamController/StreamController/assets/100139110/282d2033-7b47-43b2-aa34-72ca1f36e252)
-----

**Comment by Data-007** [comment]
Don't see an option to load any graphic

**Comment by Core447** [comment]
You can add custom icons by clicking on the large preview of the button:
![image](https://github.com/StreamController/StreamController/assets/100139110/f358ede0-afa0-4377-b468-3795f92980ee)

**Comment by Data-007** [comment]
Thanks I get it now.
