### ISSUE TITLE
Feature Request: Change Import UI

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#52]
**Describe the feature idea**
It might make more sense for the import functionality to be moved to both the main menu (hamburger menu next to minimise, maximise, close), and as an additional button when an instance is opened that does not contain any pages for those who are migrating from another application, next to the existing "Create New" button.

Not an important feature for now, but if you ever add an importer for boatswain in the future, it might be useful.

**Comment by Core447** [comment]
Tbh I'm not sure if it makes sense to move the menu entry over to the main window. But I agree that we should definitely add an import button to the "No pages" screen.

I can work on an importer for Boatswain, just want to sort everything out with the streamdeck-linux-gui one before doing that. A problem might be that Boatswain has profiles and pages, StreamController has only profiles (called pages in the app, but Boatswain calls them profiles). Either I implement this in StreamController or just convert it (for now)

**Comment by v4u6h4n** [comment]
Sounds good to me :-)

**Comment by Core447** [comment]
I added an import button to the "No pages" page with b497654c0eca7fe5db37c3006fe46a0db6fcf5cb
