### ISSUE TITLE
BUG  Flatpak is missing requirements on Mint

### ISSUE THREAD

**Issue by FreeBSD-fan** [StreamController/StreamController#58]
I just did a fresh install of Mint Cinnamon.  I also fresh installed StreamController.  It doesn't find my deck because it's missing required software.  Flatpaks MUST contain everything an application needs to run.

**Comment by Core447** [comment]
I tried it on a fresh install of Linux mint (21.3) and I could not reproduce this issue. What exactly is missing?

Edit: I had to add some udev rules before Mint was able to find my deck. Please add them with: `sudo wget https://raw.githubusercontent.com/StreamController/StreamController/main/udev.rules -O /etc/udev/rules.d/60-streamdeck.rules` and restart your computer. Unfortunately this cannot be done automatically from the Flatpak

**Comment by v4u6h4n** [comment]
Yeah same shit with the OpenRGB flatpak if I remember correctly.

**Comment by Core447** [comment]
Newer versions of udev no longer require the additional rules, but apparently Mint still ships a quite old one

**Comment by v4u6h4n** [comment]
It is same on Ubuntu? If so might be worth mentioning on Flathub page...

**Comment by Core447** [comment]
It seams to work on Ubuntu. I think I'll add an info label to the "No Decks Available" screen
