### ISSUE TITLE
BUG: Missing Images from Welcome Window

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#59]
**Describe the bug**
Multi deck support and be more productive pages have missing icons/images.

**Comment by ImDevinC** [comment]
Does this still happen? I'm not able to reproduce on 1.5.0-beta.4. If you are able to reproduce, can you run from the command line (`python main.py` or `flatpak run com.core447.StreamController`) and provide the output?

**Comment by Core447** [comment]
> I'm not able to reproduce on 1.5.0-beta.4.

It's not an issue everyone has, because it only shows up if the needed icons are missing from the installed icon sets. However, the next release should fix this by shipping the needed icons with the app.

**Comment by Core447** [comment]
Can you please check if this is still an issue for you? You can let the app show the dialog at the next start by running this command: `rm ~/.var/app/com.core447.StreamController/data/.skip-onboarding`

**Comment by v4u6h4n** [comment]
Fixed!
