### ISSUE TITLE
Add an option for autostart

### ISSUE THREAD

**Issue by Caralluin** [StreamController/StreamController#71]
The feature to add the application to the autostart is obviously useful, but it should be choosable by the user whether to add it or not. Currently the application just always registers itself for autostart when it run, which in my opinion is just kind of rude behavior. Especially for new users just testing the app this could also be quite confusing.

**Comment by Core447** [comment]
Would you prefer an option in the on-boarding dialog or in the settings (that one would be opt-out)?

**Comment by Caralluin** [comment]
Perhaps ideally both? The on-boarding dialog would be not enough, because it appears only once, so you would have no chance to change your mind later. But having it there as well would have the advantage to make it immediately clear to new users.

**Comment by v4u6h4n** [comment]
Agreed RE both.

**Comment by jslay88** [comment]
On-boarding wizard which goes over some basics (like the OS plugin and setting up a first key) would be a welcomed addition. Within this on-boarding wizard, you could prompt for an initial set of settings with defaults set, one of which would be auto-start, and another could be start minimized. 


I think auto-start and start minimized are both important features for something like this.

**Comment by v4u6h4n** [comment]
Good thinking, given that some plugins are kind of no brainers, you could have a page with a couple recommended plugins, like the deckplugin, and a simple install button next to each. But yeah, you don't want the startup wizard to be too busy as well, so understand if that adds a bit too much.

**Comment by Core447** [comment]
I think a fully fledged tutorial in the app is a bit to much, even though it would be cool, but for now we have to prioritize other features and bug fixes.

The recommended plugins section is a great idea. We could add a list of recommended plugins to the onboarding dialog with some checkboxes allowing for easy installation. We could even select some by default, like the deck plugin.
