### ISSUE TITLE
Stream Deck Pedal isn't doing anything

### ISSUE THREAD

**Issue by destiper** [StreamController/StreamController#83]
No actions assigned to the Pedal are being reproduced
I have tried hotkeys, mouse click emulation and other miscellaneous actions but the pedal doesn't do anything on keypress

**Comment by Core447** [comment]
I'll look into this. This might be fixed on the head of main. The flatpak will get updated in the next days.

**Comment by FriedrichFroebel** [comment]
I did not yet have the chance to test the application, but does this mean that the pedal is indeed supported? According to the Flatpak description at https://github.com/StreamController/StreamController/blob/88ef0798a0d0f260e8d486fb96f58a7105018596/flatpak/com.core447.StreamController.metainfo.xml#L372-L379 it is not for now.

**Comment by destiper** [comment]
Pedal is working well in recent few updates, I apologise for not closing sooner

**Comment by Core447** [comment]
> I did not yet have the chance to test the application, but does this mean that the pedal is indeed supported? According to the Flatpak description at

It is supported, but I forgot to add it to the metainfo, I'm going to update it for the next release.
