### ISSUE TITLE
wake from sleep loses connection

### ISSUE THREAD

**Issue by craigers521** [StreamController/StreamController#85]
**Describe the bug**
When i wake my machine from sleep the app loses connection with the deck, i have to force quit the app then restart it again for it reconnect

**To Reproduce**
Let machine sleep, wake from sleep, no work

**Expected behavior**
resumes connection to deck on wake

**Additional context**
Running bazzite, which is fedora silveblue based.  StreamController install from flatpak.  Works fine on initial boot, but after sleep i have to force kill the PID.  If i open the app after waking from sleep it says no decks found.  The buttons on the deck are not functional until i kill the pid and the restart it, then everything resumes working again normally.

**Comment by Core447** [comment]
Thanks for reporting this. As discussed in #41 this is already fixed, but not yet available in the Flatpak.

**Comment by craigers521** [comment]
Thats my bad @Core447 , i did search open issues for "sleep" and not "suspend", closing this out as a duplicate
