### ISSUE TITLE
BUG: Plugin store load in a infinite way on 1.5.0-beta.1

### ISSUE THREAD

**Issue by amenophis** [StreamController/StreamController#90]
**Describe the bug**
I upgraded to 1.5.0-beta.1 and since I have an infinite loader opening the Plugin store.

**To Reproduce**
1. Open the application
2. Click on the "Hamburger menu" on the top left
3. Select the first item (Open the store)
4. See the loader ...

**Expected behavior**
The Plugin store should display Plugins

**Screenshots**
![image](https://github.com/StreamController/StreamController/assets/2158235/9a35f47d-375d-442c-beb6-e77102fe374b)

**Comment by Core447** [comment]
~~Can you please check for error messages by running the app from the command line? To do so, you first have to close the running instance from the hamburger menu close action.~~

Edit: I found the bug, it seems to be related to the LocaleManager. This will be fixed soon

**Comment by Core447** [comment]
Should be fixed with: c965935dec0446e1af35d482046a06c92519d72e. Because this won't hit the flatpak immediately, I updated the old manifests. Can you please try again?

**Comment by amenophis** [comment]
Tested locally, It's now OK !
