### ISSUE TITLE
BUG: Settings view labels are broken on 1.5.0-beta.1

### ISSUE THREAD

**Issue by amenophis** [StreamController/StreamController#91]
**Describe the bug**
Many labels are missing from the Setting view

**To Reproduce**
1. open the application
2. Click on the "Hamburger menu" on top right
3. Select "Open parameters"
4. See missing labels

**Expected behavior**
Labels should be displayed

**Screenshots**
![image](https://github.com/StreamController/StreamController/assets/2158235/4645c002-c45f-4e7e-9262-4288c1c3c02d)
![image](https://github.com/StreamController/StreamController/assets/2158235/69041bab-87fe-4333-8eef-0e4a962f8f9a)
![image](https://github.com/StreamController/StreamController/assets/2158235/ef8f05fe-c6d2-4f4d-973f-936749daf09f)
![image](https://github.com/StreamController/StreamController/assets/2158235/4aca4db3-abe9-410d-a27b-b84157ec2611)
![image](https://github.com/StreamController/StreamController/assets/2158235/a84ee454-624e-4c4a-a491-b56580db9697)

**Comment by amenophis** [comment]
Same thing for Page selector view
![image](https://github.com/StreamController/StreamController/assets/2158235/4cdefe1a-ef42-4ce7-a2e5-42e57f281c06)

**Comment by Core447** [comment]
Seams like the new LocaleManager has some problems...

**Comment by Core447** [comment]
Should be fixed with a147a15ad5fd6dcfdeecfbcf4f9e24361b7215ce, but it will take some time to hit the flatpak. I'm sorry for the inconvenience.

**Comment by amenophis** [comment]
Fixed with 1.5.0-beta.2 :pray:
