### ISSUE TITLE
Videos crash the stream deck and then the app

### ISSUE THREAD

**Issue by Rcomian** [StreamController/StreamController#99]
**Describe the bug**
When using videos for the background or the screensaver, they work fine until the point that they loop, at which point everything freezes. The app stays responsive for a time, but eventually freezes too.

**To Reproduce**
1. Go to Deck Settings
2. Click on Media to show
3. Choose an .mp4 video, for example from here: https://videos.pexels.com/video-files/5680034/5680034-hd_1920_1080_24fps.mp4
4. Click on "Loop" so that the video loops
5. Set the stream deck to sleep so that it plays the video
6. After playing the video once, the animation stops and the deck goes unresponsive. The App will also freeze eventually

**Expected behavior**
The video should play at the brightness and loop repeatedly

**Other Info**
Using the 15 key streamdeck mk.2
StreamController from flatpak v1.5.0-beta.3
Gentoo on hyprland, kernel 6.8.9

[stream-controller.log](https://github.com/StreamController/StreamController/files/15225489/stream-controller.log)

**Comment by Core447** [comment]
Should be fixed with 616266b063ca71d5562cd312efb6ec94bfe2ff22
